plugins {
    id 'com.android.application'
}

android {
    namespace 'sk.radiorock.now'
    compileSdk 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        applicationId "sk.radiorock.now"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}

